# AUTOGENERATED! DO NOT EDIT! File to edit: plot-matplotlib.ipynb (unless otherwise specified).

__all__ = ['plot2D']

# Cell
import matplotlib.pyplot as plt
import numpy as np
# 支持中文显示
plt.rcParams['font.sans-serif'] = ['Arial Unicode MS']
plt.rcParams['axes.unicode_minus'] = False

# Cell
def plot2D(func_list, xRange, num=1000, xlabel='x', ylabel='f(x)'):
    """
    绘制2D函数图像
    e.g.
        plot2D(np.tanh, [-2, 2])
    :param func:
    :param xRange:
    :return:
    """
    xArr = np.linspace(xRange[0], xRange[1], num=num)
    plt.grid(True)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    for func in func_list:
        plt.plot(xArr, func(xArr))
    plt.legend([str(f) for f in func_list])
    plt.show()