# AUTOGENERATED! DO NOT EDIT! File to edit: algo-dl-acitivation_function.ipynb (unless otherwise specified).

__all__ = ['sigmoid', 'softmax']

# Cell
def sigmoid(x):
    """
    sigmoid function or logistic function is used as a hypothesis function in classification problems
    """
    return 1 / (1 + np.exp(-x))

# Cell
def softmax(x):
    """

    :param x: array
    :return:
    """
    exp = np.exp(arr1d - arr1d.max())  # 防止指数爆炸
    return exp / np.sum(exp)