# AUTOGENERATED! DO NOT EDIT! File to edit: algo-dl-loss_funtion.ipynb (unless otherwise specified).

__all__ = ['square_loss']

# Cell
def square_loss(y_true, y_hat):
    return 0.5 * np.power((y_true - y_hat), 2)