# AUTOGENERATED! DO NOT EDIT! File to edit: engineering_concurrency.ipynb (unless otherwise specified).

__all__ = ['ClockProcess', 'ClockThread']

# Cell
class ClockProcess(Process):
    def __init__(self, interval):
        Process.__init__(self)
        self.interval = interval
    def run(self):
        from time import sleep
        print('子进程开始')
        sleep(self.interval)
        print('子进程结束')

# Cell
class ClockThread(Thread):
    def __init__(self, interval):
        Thread.__init__(self)
        self.interval = interval
    def run(self):
        print('子线程开始')
        sleep(self.interval)
        print('子线程结束')