# AUTOGENERATED! DO NOT EDIT! File to edit: utils_json.ipynb (unless otherwise specified).

__all__ = ['write2json_file', 'read_from_json_file']

# Cell
try:
    import ujson as json
    print('ujson')
except:
    import json

# Cell
def write2json_file(fp, data, encoding='utf-8'):
    """
    Converts arbitrary object recursively into JSON file.
    Use ensure_ascii=false to output UTF-8.
    """
    with open(fp, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False)

# Cell
def read_from_json_file(fp, encoding='utf-8'):
    with open(fp, 'r', encoding='utf-8') as f:
        data1 = json.load(f)
    return data1