# AUTOGENERATED! DO NOT EDIT! File to edit: utils_time.ipynb (unless otherwise specified).

__all__ = ['time_cost']

# Cell
def time_cost(func):
    """
    记录函数运行时间
    """
    import time

    def wrapper(*args, **kvargs):
        tic = time.time()
        result = func(*args, **kvargs)
        toc = time.time()
        print('{} is called. {}s is used.'.format(func.__name__, toc - tic))
        return result

    return wrapper