# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"parser": "config.ipynb",
         "args": "config.ipynb",
         "test_dir": "0EDA.ipynb",
         "train_dir": "0EDA.ipynb",
         "get_trainset_raw": "0EDA.ipynb",
         "get_ad_feat": "0EDA.ipynb",
         "get_valset_raw": "0EDA.ipynb",
         "get_testset_raw": "0EDA.ipynb",
         "val": "0EDA.ipynb"}

modules = ["config.py",
           "eda.py"]

doc_url = "https://ian.github.io/tx/"

git_url = "https://github.com/ian/tx/tree/master/"

def custom_doc_links(name): return None
