# AUTOGENERATED! DO NOT EDIT! File to edit: algo_rs_search_vector_faiss.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
def say_hello(to):
    """

    """
    return f'Hello {to}!'