# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"trace": "3_model_new.ipynb",
         "recall_from_user_item_matr": "3_model_new.ipynb",
         "recall_from_cocur_matr": "3_model_new.ipynb",
         "parser": "3_model_new.ipynb",
         "args": "3_model_new.ipynb",
         "whole_click": "3_model_new.ipynb",
         "save_dir": "3_model_new.ipynb",
         "sr1": "3_model_new.ipynb"}

modules = ["train.py"]

doc_url = "https://ian.github.io/code/"

git_url = "https://github.com/ian/code/tree/master/"

def custom_doc_links(name): return None
