# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/config.ipynb (unless otherwise specified).

__all__ = ['parser', 'args']

# Cell

import argparse

parser = argparse.ArgumentParser(description='t')
parser.add_argument('--now_phase', type=int, default=6, help='')
parser.add_argument('--window', type=int, default=10, help='cocur_matr的时间窗')
parser.add_argument('--time_decay', type=float, default=7/8, help='时间衰减')
parser.add_argument('--submit_fp', type=str, default='/Users/luoyonggui/Downloads/baseline1_itemcf4.csv', help='提交文件生成位置')
parser.add_argument('--mode', type=str, default='train', help='train test')
parser.add_argument('--topk', type=int, default=500, help='每种召回策略召回的样本数')
parser.add_argument('--DATA_DIR', type=str, default='../../data/contest/kdd_debiasing', help='data dir')

args = parser.parse_args(args=[])