# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_whole_click_data": "0EDA.ipynb"}

modules = ["eda.py"]

doc_url = "https://ian.github.io//"

git_url = "https://github.com/ian//tree/master/"

def custom_doc_links(name): return None
