# AUTOGENERATED! DO NOT EDIT! File to edit: data-structure-string.ipynb (unless otherwise specified).

__all__ = ['remove_non_chinese_char']

# Cell
def remove_non_chinese_char(context):
    import re
    filtrate = re.compile(u'[^\u4E00-\u9FA5|a-zA-Z0-9/]')  # non-Chinese unicode range
    context = filtrate.sub(r'', context)  # remove all non-Chinese characters
    return context