# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"parser": "config.ipynb",
         "args": "config.ipynb"}

modules = ["config.py"]

doc_url = "https://ian.github.io/code/"

git_url = "https://github.com/ian/code/tree/master/"

def custom_doc_links(name): return None
