# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/config.ipynb (unless otherwise specified).

__all__ = ['parser', 'args']

# Cell

import argparse

parser = argparse.ArgumentParser(description='t')

parser.add_argument('--DATA_DIR', type=str, default='../../../mydata/data_origin/chip_medner/', help='data dir')
parser.add_argument('--DATA_GEN', type=str, default='../../../mydata/data_gen/chip_medner/', help='data gen')

args = parser.parse_args(args=[])