# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "utils_functools.ipynb",
         "alibox": "active_learning.ipynb",
         "model": "active_learning.ipynb",
         "stopping_criterion": "active_learning.ipynb",
         "QBCStrategy": "active_learning.ipynb",
         "QBC_result": "active_learning.ipynb",
         "analyser": "active_learning.ipynb",
         "sigmoid": "algo-dl-acitivation_function.ipynb",
         "softmax": "algo-dl-acitivation_function.ipynb",
         "square_loss": "algo-dl-loss_funtion.ipynb",
         "val": "algo_ml_tree_catboost.ipynb",
         "predict": "algo_ml_tree_catboost.ipynb",
         "explain": "algo_ml_tree_catboost.ipynb",
         "Apriori": "algo_rs_match_associated_rules.ipynb",
         "build_co_occurance_matrix": "algo_rs_match_matrix.ipynb",
         "load_co_occurance_matrix": "algo_rs_match_matrix.ipynb",
         "build_user_item_matrix": "algo_rs_match_matrix.ipynb",
         "build_item_item_cosine_matrix": "algo_rs_match_matrix.ipynb",
         "buildTfidf": "algo_seq_features_extraction_text.ipynb",
         "describe": "data-processing-eda.ipynb",
         "aggregate_features": "data-processing-eda.ipynb",
         "ClockProcess": "engineering_concurrency.ipynb",
         "ClockThread": "engineering_concurrency.ipynb",
         "HelloSayer": "engineering_nbdev.ipynb",
         "plot2D": "plot-matplotlib.ipynb",
         "write2json_file": "utils_json.ipynb",
         "read_from_json_file": "utils_json.ipynb",
         "PickleWrapper": "utils_pickle.ipynb",
         "time_cost": "utils_time.ipynb"}

modules = ["engineering/nbdev.py",
           "active_learning.py",
           "algo/dl/acitivation_function.py",
           "algo/dl/loss_funtion.py",
           "algo/ml/tree/catboost.py",
           "algo/rs/match/associated_rules.py",
           "algo/rs/match/matrix.py",
           "algo/rs/search/vector/faiss.py",
           "algo/seq/features_extraction/text.py",
           "data/processing/eda.py",
           "engineering/concurrency.py",
           "engineering/snorkel.py",
           "plot/matplotlib.py",
           "utils/functools.py",
           "utils/json.py",
           "utils/pickle.py",
           "utils/time.py"]

doc_url = "https://ian.github.io/mylib/"

git_url = "https://github.com/ian/mylib/tree/master/"

def custom_doc_links(name): return None
