# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "engineering_nbdev.ipynb",
         "val": "algo_ml_shallow_tree_catboost.ipynb",
         "predict": "algo_ml_shallow_tree_catboost.ipynb",
         "explain": "algo_ml_shallow_tree_catboost.ipynb",
         "Apriori": "algo_rs_associated_rules.ipynb",
         "build_co_occurance_matrix": "algo_rs_matrix.ipynb",
         "load_co_occurance_matrix": "algo_rs_matrix.ipynb",
         "build_user_item_matrix": "algo_rs_matrix.ipynb",
         "build_item_item_cosine_matrix": "algo_rs_matrix.ipynb",
         "HelloSayer": "engineering_nbdev.ipynb"}

modules = ["engineering/nbdev.py",
           "algo/ml/shallow/tree/catboost.py",
           "rs/associated_rules.py",
           "algo/rs/matrix.py"]

doc_url = "https://ian.github.io/mylib/"

git_url = "https://github.com/ian/mylib/tree/master/"

def custom_doc_links(name): return None
