# AUTOGENERATED! DO NOT EDIT! File to edit: 0EDA.ipynb (unless otherwise specified).

__all__ = []

# Cell
import os
from code.config import DATA_DIR
from loguru import logger
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', 100)  # 设置显示数据的最大列数，防止出现省略号…，导致数据显示不全
pd.set_option('expand_frame_repr', False)  # 当列太多时不自动换行

from sklearn.metrics import classification_report, accuracy_score
from .utils.pickle import PickleWrapper