# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/config.ipynb (unless otherwise specified).

__all__ = ['parser', 'args']

# Cell

import argparse

parser = argparse.ArgumentParser(description='t')

parser.add_argument('--DATA_DIR', type=str, default='../../data/contest/20kdxf/', help='data dir')

args = parser.parse_args(args=[])